---
title: "Excercise 1 Market Segmentation_pca"
author: "TiffS"
date: "8/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

```{r}
sm = read.csv(url("https://raw.githubusercontent.com/jgscott/STA380/master/data/social_marketing.csv"))
Z = scale(sm[,-1],center = T,scale = T)
```

```{r}
smpca = prcomp(as.matrix(Z), scale=TRUE, rank=2)
loadings = smpca$rotation
scores = smpca$x
```
```{r}
std_dev = smpca$sdev
pca_var = std_dev^2
prop_var <- pca_var/sum(pca_var)
plot(prop_var[c(1:10)], xlab = "Principal Component", ylab = "Proportion of Variance Explained",
type = "b")
```
```{r}
std_dev = smpca$sdev
pca_var = std_dev^2
prop_var <- pca_var/sum(pca_var)
plot(cumsum(prop_var), xlab = "Principal Component", ylab = "Proportion of Variance Explained",
type = "b")
```


```{r}
biplot(smpca)
```
```{r}
scores_plot = as.data.frame(smpca$x)
ggplot(data = scores_plot, aes(x = PC1, y = PC2, label = rownames(scores_plot))) +
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  geom_text(colour = "salmon3", alpha = 0.8, size = 4)
```

```{r}
qplot(scores[,1], scores[,2], xlab='Component 1', ylab='Component 2')
```

```{r}

```

